#!/usr/bin/env ruby
# frozen_string_literal: true

# WeBER: Web Browser Engineering in Ruby
#
# Robert Haines
#
# Public Domain

require 'rubygems'
require 'bundler/setup'

require_relative 'lib/weber'

DEFAULT_FILE = ::File.expand_path('README.md', __dir__)

uri = ARGV[0] || "file://#{DEFAULT_FILE}"
puts WeBER::Browser.load(uri)
